In [1]:
import numpy as np

In [2]:
a = np.array([1010, 1000, 990])
np.exp(a) / np.sum(np.exp(a))

/var/folders/cx/pwvnmd2s0f1464n59r3vjng80000gp/T/ipykernel_13510/832863605.py:2: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))
/var/folders/cx/pwvnmd2s0f1464n59r3vjng80000gp/T/ipykernel_13510/832863605.py:2: RuntimeWarning: invalid value encountered in true_divide
  np.exp(a) / np.sum(np.exp(a))


array([nan, nan, nan])

In [3]:
c = np.max(a)
a - c

array([  0, -10, -20])

In [4]:
np.exp(a - c) / np.sum(np.exp(a - c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [7]:
def softmax(a):
  c = np.max(a)
  exp_a = np.exp(a - c)
  sum_exp_a = np.sum(exp_a)
  y = exp_a / sum_exp_a

  return y

In [8]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]


In [9]:
np.sum(y)

1.0